apiVersion: v1
kind: Service
metadata:
  name: {{ include "jumpbox.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jumpbox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.hostNetwork }}
  clusterIP: None
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.portName }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "jumpbox.selectorLabels" . | nindent 4 }}
